title: "J3RN's Blog"
email: jonarnett90@gmail.com
description: >-
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: _J3RN
url: https://blog.j3rn.com
github_username:  J3RN

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
