title: J3RN's Blog
email: jonarnett90@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
description: My technical blog where I write about Ruby, Elixir, software architecture, software development methodologies, and programming language design
url: https://blog.j3rn.com
github_username:  J3RN
social:
  name: Jonathan Arnett
  links:
    - https://github.com/J3RN
    - https://linkedin.com/in/j3rn
header_pages:
  - index.html

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
google_analytics: true # Actually Plausible, but Minima forces this name
