baseURL = "http://j3rn.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "J3RN's Blog"
theme = "congo"

[author]
name = "Jonathan Arnett"
image = "images/avatar.png"
links = [
  { mastodon = "https://fosstodon.org/@j3rn" }
]

[social]
github = "https://github.com/J3RN"
mastodon = "https://fosstodon.org/J3RN"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
author = "Jonathan Arnett"
description = "My technical blog where I write about Ruby, Elixir, software architecture, software development methodologies, and programming language design."
enableRSS = true
colorScheme = "congo"
logo = "avatar.png"
enableSearch = true
# Doesn't work
# enableCodeCopy = true

[params.footer]
showAppearanceSwitcher = true

[params.plausible]
domain = "j3rn.com"

[params.homepage]
layout = "custom"
showRecent = true

[params.article]
showDate = true
showAuthor = false
dateFormat = "2006-01-02"
# Interesting idea; ignoring for now
# showEdit = true
# editURL = "https://github.com/J3RN/blog/edit/master/content/"
showTaxonomies = true
# sharingLinks = ["twitter", "reddit", "linkedin"]

# Required me to change Congo and even so made the list look cluttered
# [params.list]
# showSummary = true

[params.page]
showDate = false

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style='doom-one'

[[menus.main]]
name = "Tags"
pageRef = "tags"
weight = 30
