baseURL = "http://j3rn.com/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "J3RN's Blog"
theme = "congo"

[author]
name = "Jonathan Arnett"
image = "images/avatar.png"

[social]
github = "https://github.com/J3RN"

[params]
author = "Jonathan Arnett"
description = "My technical blog where I write about Ruby, Elixir, software architecture, software development methodologies, and programming language design."
enableRSS = true
colorScheme = "congo"
darkToggle = true
logo = "avatar.png"

[params.plausible]
domain = "j3rn.com"

[params.homepage]
layout = "custom"
showRecent = true

[params.article]
showDate = true
showAuthor = false
dateFormat = "2006-01-02"

[params.page]
showDate = false

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style='vim'

[[menus.main]]
name = "Tags"
pageRef = "tags"
weight = 30
